# Generated by Django 5.1.2 on 2024-12-29 10:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_created_by_booking_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'paymentmethod',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_booking_status',
            field=models.CharField(choices=[('default', 'default'), ('booked', 'booked'), ('empty', 'empty')], default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='room_maintenance_status',
            field=models.CharField(choices=[('default', 'Default'), ('cleaned', 'Cleaned'), ('used', 'Used'), ('broken', 'Broken')], default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rate_type',
            field=models.CharField(choices=[('member', 'Member'), ('non-member', 'Non-Member')], default='non-member', max_length=255),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('issued_to', models.CharField(max_length=255)),
                ('receipt_number', models.CharField(db_index=True, max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('amount_available', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_status', models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=255)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.receipt'),
        ),
    ]
