# Generated by Django 5.1.2 on 2025-02-08 11:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shiftstatus_profileshiftassign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('note_date', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_notes', to='api.profile')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_shift_notes', to='api.profile')),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_notes', to='api.shift')),
            ],
            options={
                'verbose_name': 'Shift Note',
                'verbose_name_plural': 'Shift Notes',
                'db_table': 'shiftnote',
            },
        ),
    ]
