# Generated by Django 5.1.2 on 2025-02-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shiftnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftnote',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shift_notes', to='api.profileshiftassign'),
        ),
    ]
