# Generated by Django 5.1.2 on 2025-02-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shiftnote_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileshiftassign',
            options={'ordering': ['-date'], 'verbose_name': 'Shift Assignment', 'verbose_name_plural': 'Shift Assignments'},
        ),
    ]
