# Generated by Django 5.1.2 on 2024-12-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booking_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_guests',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
