# Generated by Django 5.1.2 on 2025-02-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profileshiftassign_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftnote',
            old_name='shift',
            new_name='assigned_shift',
        ),
    ]
