# Generated by Django 5.1.2 on 2025-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_shift_shiftnote_assigned_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileshiftassign',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileshiftassign',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
