# Generated by Django 5.1.2 on 2024-12-29 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_booking_checked_out_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Complaint Status',
                'verbose_name_plural': 'Complaint Statuses',
                'db_table': 'complaintstatus',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hashtag',
                'verbose_name_plural': 'Hashtags',
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Priority',
                'verbose_name_plural': 'Priorities',
                'db_table': 'priority',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('complaint_items', models.ManyToManyField(to='api.amenity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to='api.profile')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.complaintstatus')),
                ('hashtags', models.ManyToManyField(to='api.hashtag')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.priority')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='AssignComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='api.profile')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to='api.profile')),
                ('assigned_to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaint')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.complaintstatus')),
            ],
            options={
                'verbose_name': 'Assign Complaint',
                'verbose_name_plural': 'Assign Complaints',
                'db_table': 'assigncomplaint',
            },
        ),
        migrations.CreateModel(
            name='ProcessComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaint')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.complaintstatus')),
            ],
            options={
                'verbose_name': 'Process Complaint',
                'verbose_name_plural': 'Process Complaints',
                'db_table': 'processcomplaint',
            },
        ),
    ]
