# Generated by Django 5.1.2 on 2025-02-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profileshiftassign_time_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomkeepingassign',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments', to='api.priority'),
        ),
    ]
