# Generated by Django 5.1.2 on 2025-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_roomkeepingassign_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomkeepingassign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
