# Generated by Django 5.1.2 on 2024-12-31 08:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_complaintstatus_hashtag_priority_complaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='client',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='complaint_items',
            field=models.ManyToManyField(to='api.amenity'),
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='hashtags',
            field=models.ManyToManyField(to='api.hashtag'),
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.priority'),
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='room_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='api.amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.roomcategory'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='amenities',
            field=models.ManyToManyField(to='api.amenity'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_booking_status',
            field=models.CharField(choices=[('default', 'default'), ('booked', 'booked'), ('empty', 'empty'), ('unavailable', 'unavailable')], default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
            ],
            options={
                'verbose_name': 'Bed Type',
                'verbose_name_plural': 'Beds Types',
                'db_table': 'bedtype',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='api.bedtype'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bed_types',
            field=models.ManyToManyField(to='api.bedtype'),
        ),
    ]
