# Generated by Django 5.1.2 on 2025-01-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_complaint_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='room_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
    ]
