# Generated by Django 5.1.2 on 2025-02-19 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_roomkeepingassign_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processroomkeeping',
            name='room_state_trans',
        ),
        migrations.AlterModelOptions(
            name='processroomkeeping',
            options={'verbose_name': 'Process Room Keeping', 'verbose_name_plural': 'Process Room Keepings'},
        ),
        migrations.RemoveField(
            model_name='processroomkeeping',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='processroomkeeping',
            name='note',
        ),
        migrations.RemoveField(
            model_name='processroomkeeping',
            name='room',
        ),
        migrations.RemoveField(
            model_name='processroomkeeping',
            name='shift',
        ),
        migrations.AddField(
            model_name='processroomkeeping',
            name='room_number',
            field=models.CharField(default='na', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processroomkeeping',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.housekeepingstate'),
        ),
        migrations.AddField(
            model_name='roomkeepingassign',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.housekeepingstate'),
        ),
        migrations.AlterField(
            model_name='processroomkeeping',
            name='room_keeping_assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_keeping_processes', to='api.roomkeepingassign'),
        ),
        migrations.DeleteModel(
            name='HouseKeepingStateTrans',
        ),
    ]
