# Generated by Django 5.1.2 on 2025-01-01 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_complaint_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigncomplaint',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complaints', to='api.complaint'),
        ),
        migrations.AlterField(
            model_name='processcomplaint',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_complaints', to='api.complaint'),
        ),
        migrations.AlterField(
            model_name='processcomplaint',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_complaints', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='processcomplaint',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_complaints', to='api.complaintstatus'),
        ),
        migrations.CreateModel(
            name='ComplaintAssignLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaint_logs', to='api.profile')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned_logs', to='api.profile')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complaint_logs', to='api.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Assign Log',
                'verbose_name_plural': 'Complaint Assign Logs',
                'db_table': 'complaintassignlog',
                'ordering': ['-date_assigned'],
            },
        ),
    ]
