# Generated by Django 5.1.2 on 2025-01-01 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_assigncomplaint_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintassignlog',
            name='assigned_complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_assign_logs', to='api.assigncomplaint'),
        ),
        migrations.AddField(
            model_name='complaintassignlog',
            name='complaint_assign_status',
            field=models.CharField(choices=[('department', 'Transfer to Department'), ('staff', 'Transfer to Staff'), ('resolved', 'Resolved'), (None, 'Default')], max_length=255, null=True),
        ),
    ]
