# Generated by Django 5.1.2 on 2025-01-01 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_complaintassignlog_assigned_complaint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigncomplaint',
            options={'ordering': ['-created_on'], 'verbose_name': 'Assign Complaint', 'verbose_name_plural': 'Assign Complaints'},
        ),
        migrations.RemoveField(
            model_name='assigncomplaint',
            name='date_resolved',
        ),
        migrations.RemoveField(
            model_name='assigncomplaint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='date_resolved',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='processcomplaint',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='processcomplaint',
            name='date_resolved',
        ),
        migrations.RemoveField(
            model_name='processcomplaint',
            name='status',
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='complaint_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.complaintstatus'),
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_complaints', to='api.profile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processcomplaint',
            name='assigned_complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assigncomplaint'),
        ),
        migrations.AddField(
            model_name='processcomplaint',
            name='complaint_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_complaints', to='api.complaintstatus'),
        ),
        migrations.AddField(
            model_name='processcomplaint',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processcomplaint',
            name='process_complaint_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processcomplaint',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assigncomplaint',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='processcomplaint',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_complaints', to='api.complaint'),
        ),
        migrations.DeleteModel(
            name='ComplaintAssignLog',
        ),
    ]
