# Generated by Django 5.1.2 on 2025-02-20 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_roomkeepingassign_member_shifts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomkeepingassign',
            name='status',
        ),
        migrations.CreateModel(
            name='ProcessRoomKeeping2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('room_keeping_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_keeping_status_processes', to='api.roomkeepingassign')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.housekeepingstate')),
            ],
            options={
                'verbose_name': 'Process Room Keeping',
                'verbose_name_plural': 'Process Room Keepings',
                'db_table': 'processroomkeeping2',
            },
        ),
        migrations.AddField(
            model_name='roomkeepingassign',
            name='status',
            field=models.ManyToManyField(related_name='room_assignments', through='api.ProcessRoomKeeping', to='api.housekeepingstate'),
        ),
    ]
