# Generated by Django 5.1.2 on 2025-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_roomkeepingassign_status_processroomkeeping2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processroomkeeping2',
            options={'ordering': ['-date_created'], 'verbose_name': 'Process Room Keeping', 'verbose_name_plural': 'Process Room Keepings'},
        ),
        migrations.AlterModelOptions(
            name='roomkeepingassign',
            options={'ordering': ['-date_created'], 'verbose_name': 'Room Keeping Assignment', 'verbose_name_plural': 'Room Keeping Assignments'},
        ),
        migrations.AddField(
            model_name='roomkeepingassign',
            name='current_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
