# Generated by Django 5.1.2 on 2025-02-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_processroomkeeping2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomkeepingassign',
            name='task_supported',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
