# Generated by Django 5.1.2 on 2025-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_roomkeepingassign_task_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomkeepingassign',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
