# Generated by Django 5.1.2 on 2025-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_roomkeepingassign_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingstate',
            name='allow_only_managers',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='housekeepingstate',
            name='set_to_unfinished_after_task_expiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
