# Generated by Django 5.1.2 on 2025-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_housekeepingstate_allow_only_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingstate',
            name='allow_after_task_is_ended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
