# Generated by Django 5.1.2 on 2025-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_housekeepingstate_allow_after_task_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftstatus',
            name='change_after_expiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
