# Generated by Django 5.1.2 on 2025-02-26 12:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_shiftstatus_change_after_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Arrival Mode',
                'verbose_name_plural': 'Arrival Modes',
                'db_table': 'arrivalmode',
            },
        ),
        migrations.CreateModel(
            name='VIPStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'VIP Status',
                'verbose_name_plural': 'VIP Statuses',
                'db_table': 'vipstatus',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sponsor_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='title',
        ),
        migrations.RemoveField(
            model_name='client',
            name='national_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_younger_guests',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.arrivalmode'),
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
                'db_table': 'loyaltyprogram',
            },
        ),
        migrations.CreateModel(
            name='ClientLoyaltyPrograms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_enrolled', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='api.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'Client Loyalty Program',
                'verbose_name_plural': 'Client Loyalty Programs',
                'db_table': 'clientloyaltyprograms',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='loyalty_program',
            field=models.ManyToManyField(related_name='clients', through='api.ClientLoyaltyPrograms', to='api.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vip_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vipstatus'),
        ),
    ]
