# Generated by Django 5.1.2 on 2025-02-27 07:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_arrivalmode_vipstatus_remove_booking_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientloyaltyprograms',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientloyaltyprograms',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientloyaltyprograms',
            name='loyalty_program',
        ),
        migrations.RemoveField(
            model_name='assigncomplaint',
            name='client',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checked_out',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='client',
        ),
        migrations.AddField(
            model_name='assigncomplaint',
            name='guest',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='guest',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.roomcategory'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.roomtype'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(db_index=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gender')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.nametitle')),
            ],
            options={
                'db_table': 'Guest',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=255)),
                ('guest_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.CharField(db_index=True, max_length=255)),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_older_guests', models.PositiveIntegerField(default=1)),
                ('number_of_younger_guests', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('booking_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_out', models.BooleanField(default=False)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymenttype')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.receipt')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='api.room')),
                ('room_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.roomcategory')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.roomtype')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sponsor')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='api.guest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guest'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guest'),
        ),
        migrations.CreateModel(
            name='GuestLoyaltyPrograms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_enrolled', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='api.guest')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loyaltyprogram')),
            ],
            options={
                'verbose_name': 'Guest Loyalty Program',
                'verbose_name_plural': 'Guest Loyalty Programs',
                'db_table': 'Guestloyaltyprograms',
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='loyalty_program',
            field=models.ManyToManyField(related_name='Guests', through='api.GuestLoyaltyPrograms', to='api.loyaltyprogram'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentstatus'),
        ),
        migrations.CreateModel(
            name='SponsorClaims',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_department', models.CharField(max_length=255)),
                ('guest_employment_id', models.CharField(max_length=255)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guest')),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor Claim',
                'verbose_name_plural': 'Sponsor Claims',
                'db_table': 'sponsorclaims',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientLoyaltyPrograms',
        ),
    ]
