# Generated by Django 5.1.2 on 2025-03-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_paymentstatus_remove_booking_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'Payment Status', 'verbose_name_plural': 'Payment Statuses'},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='loyalty_program',
        ),
        migrations.AddField(
            model_name='guest',
            name='loyalty_programs',
            field=models.ManyToManyField(related_name='guests', through='api.GuestLoyaltyPrograms', to='api.loyaltyprogram'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guestloyaltyprograms',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_loyalty_programs', to='api.guest'),
        ),
        migrations.AlterModelTable(
            name='paymentstatus',
            table='paymentstatus',
        ),
    ]
